### ISSUE TITLE
Consider removing tailwind.css

### ISSUE THREAD

**Issue by jacobclevenger** [Black-Kro/kro-ui#15]
Tailwind css is a great library, but using it to write styles for this library may not be a great idea. It makes it difficult to override styles when using the library. Currently considering either removing the library or finding a way to make the styles easier to override when using it. This may be possible if we prefix the tailwind styles with something, but further testing will be required. If styles can be overridden by the users of this library, then consider converting existing styles over to mostly using tailwind.

**Comment by kayandra** [comment]
Could you expand on what makes it hard to override styles? maybe I can help

**Comment by jacobclevenger** [comment]
Yeah, so the problem is let's say I have a component that has a property like `max-w-32`. If I were to then use my library and try to do `<my-component class="max-w-12"></my-component>` it would not work since in tailwind `max-w-32` has a higher priority than `max-w-12`. Now maybe this could be fixed if I instead used @apply in my library so 3rd party users could use the classes. I haven't tested this yet though

**Comment by jacobclevenger** [comment]
I think I might go with the @apply route

**Comment by kayandra** [comment]
Oh! ran into a similar issue while trying to update height. Ended up creating a conditional array that got modified via props

**Comment by jacobclevenger** [comment]
Hmm not a bad idea. Maybe there could be a utility that would look at the classes passed down to the object and then replace related classes with the classes given to it. Something kind of like

For the library
```html
<div class="my-component" :class="tailwindStyles('h-10 rounded-full')"></div>
```
and then when using the component like
```html
<my-component class="h-4"></my-component>
```
the output might look something like
```html
<div class="my-component rounded-full h-4"></div>
```

The only annoying part might be figuring out what it should replace, but I think the way that tailwind is structured should make the relatively easy

**Comment by jacobclevenger** [comment]
Then again I'm not sure how this might affect purgecss

**Comment by kayandra** [comment]
hmmm, that could work
