### ISSUE TITLE
When there is a scrollbar on site Dialog get scewed

### ISSUE THREAD

**Issue by SatheesA** [Black-Kro/kro-ui#16]
**Describe the bug**
When you open the dialog the scrollbar on the site disappears and the whole content is skewed right. 
**To Reproduce**
go to https://ui.black-kro.dev/components/dialog
open the dialog on the page.
The scrollbar disappears and content is scewed.

**Expected behavior**
Expectation is that the content is not skewed. An example of a dialog that has scrollbar but the content is not skewed:
https://v5.getbootstrap.com/docs/5.0/components/modal/

**Desktop (please complete the following information):**
windows 10, chrome browser

**Comment by jacobclevenger** [comment]
Thanks, will look into it!

**Comment by jacobclevenger** [comment]
Fixed. But won't fixes won't be visible in the docs until I'm able to publish an updated version of the docs.
